"""Add Tables

Revision ID: 527fb5b1fe67
Revises: 
Create Date: 2023-12-11 16:11:31.392929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527fb5b1fe67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('contacts',
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('user_login', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_login'], ['users.login'], ),
    sa.PrimaryKeyConstraint('contact_email')
    )
    op.create_index(op.f('ix_contacts_user_login'), 'contacts', ['user_login'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_user_login'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
